# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by:
# Generated on: 12/3/2022

@{
    RootModule        = 'RBUtils.psm1'
    ModuleVersion     = '0.0.1'
    GUID              = 'a6b8285a-1d33-4779-b739-299781b1cd96'
    Author            = 'Raj Balgobin'
    CompanyName       = 'Unknown'
    Copyright         = '(c) . All rights reserved.'
    Description       = ''
    FunctionsToExport = @('*')
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

